src/blog/forms.py
# -*- coding:utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import SubmitField
from wtforms import SelectField
from wtforms import BooleanField
from wtforms import TextAreaField
from wtforms.validators import DataRequired
from wtforms.validators import Email
from wtforms.validators import Length
from flask_pagedown.fields import PageDownField
from model.role import Role


class PostForm(FlaskForm):
    title = StringField(label=u'博客标题', validators=[
                        DataRequired()], id='titlecode')
    body = PageDownField(label=u'博客内容', validators=[DataRequired()])
    submit = SubmitField(label=u'提交')


class CommentForm(FlaskForm):
    body = PageDownField(label=u'发表评论', validators=[DataRequired()])
    submit = SubmitField(label=u'提交')


class EditProfileForm(FlaskForm):
    name = StringField(label=u'真实姓名', validators=[Length(0, 64)])
    location = StringField(label=u'地址', validators=[Length(0, 64)])
    about_me = TextAreaField(label=u'关于我')
    submit = SubmitField(label=u'提交')


class EditProfileAdministratorForm(FlaskForm):
    email = StringField(label=u'邮箱', validators=[
                        DataRequired(), Length(1, 64), Email()])
    username = StringField(label=u'用户名', validators=[
                           DataRequired(), Length(1, 64)])
    confirmed = BooleanField(label=u'确认')
    role = SelectField(label=u'角色', coerce=int)

    name = StringField(label=u'真实姓名', validators=[Length(0, 64)])
    location = StringField(label=u'地址', validators=[Length(0, 64)])
    about_me = TextAreaField(label=u'关于我')
    submit = SubmitField(label=u'提交')

    # 初始化时要对role的复选框进行搭建
    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdministratorForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name)
                             for role in Role.query.order_by(Role.name)]
        self.user = user

src/blog/__init__.py
# -*- coding:utf-8 -*-
from flask import Blueprint
from flask import current_app
from flask_sqlalchemy import get_debug_queries
from model.permission import Permission

blog = Blueprint('blog', __name__)


@blog.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)


@blog.after_app_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= current_app.config['MISSOURI_SLOW_DB_QUERY_TIME']:
            current_app.logger.warning(
                'Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n'
                % (query.statement, query.nParameters, query.duration,
                   query.context)
            )
    return response


from . import views

src/blog/views.py
# -*- coding: utf-8 -*-
from flask import render_template
from flask import make_response
from flask import redirect
from flask import request
from flask import url_for
from flask import current_app
from flask import abort
from flask import flash
from flask_login import current_user
from flask_login import login_required
from flask_sqlalchemy import get_debug_queries
from . import blog as app
from .forms import CommentForm
from .forms import PostForm
from .forms import EditProfileForm
from .forms import EditProfileAdministratorForm
from app import db
from model.permission import Permission
from model.post import Post
from model.comment import Comment
from model.user import User
from model.role import Role
from common.decorators import permission_required

COOKIE_MAX_AGE = 30 * 24 * 60 * 60


@app.route('/', methods=['GET', 'POST'])
def index():
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed'))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    page = request.args.get('page', 1, type=int)
    pagination = query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=10, error_out=False)
    posts = pagination.items
    return render_template(
        'index.html',
        show_followed=show_followed,
        posts=posts,
        pagination=pagination)


@app.route('/all')
@login_required
def show_all():
    response = make_response(redirect(url_for('blog.index')))
    response.set_cookie('show_followed', '', max_age=COOKIE_MAX_AGE)
    return response


@app.route('/followed')
@login_required
def show_followed():
    response = make_response(redirect(url_for('blog.index')))
    response.set_cookie('show_followed', '2', max_age=COOKIE_MAX_AGE)
    return response


@app.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(
            body=form.body.data,
            post=post,
            author=current_user._get_current_object(), )
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('blog.post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) / 10 + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=10, error_out=False)
    comments = pagination.items
    return render_template(
        'post.html',
        posts=[post],
        form=form,
        comments=comments,
        pagination=pagination)


@app.route('/blog', methods=['GET', 'POST'])
@login_required
def blog():
    form = PostForm()
    if current_user.can(Permission.WRITE_ARTICLES) and \
            form.validate_on_submit():
        post = Post(
            title=form.title.data,
            body=form.body.data,
            author=current_user._get_current_object())
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('blog.index'))
    return render_template('blog.html', form=form)


@app.route('/admin')
@login_required
@permission_required(Permission.ADMINISTRATOR)
def for_admin_only():
    return u'Administrator Entrance'


@app.route('/moderator')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def for_moderator_only():
    return u'Administrator Entrance'


@app.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template('user.html', user=user, posts=posts)


@app.route('/follow/<username>')
def follow(username):
    u = User.query.filter_by(username=username).first()
    if u is None:
        flash(u'没有该用户')
        return redirect(url_for('blog.index'))
    if current_user.is_following(u):
        flash(u'已经关注了该用户')
        return redirect(url_for('blog.user', username=username))
    current_user.follow(u)
    flash(u'关注了 %s' % username)
    return redirect(url_for('blog.user', username=username))


@app.route('/unfollow/<username>')
def unfollow(username):
    u = User.query.filter_by(username=username).first()
    if u is None:
        flash(u'没有该用户')
        return redirect(url_for('blog.index'))
    if u.is_followed_by(current_user):
        current_user.unfollow(u)
        flash(u'取消对 %s 的关注' % username)
        return redirect(url_for('blog.user', username=username))


@app.route('/followers/<username>')
def followers(username):
    u = User.query.filter_by(username=username).first()
    page = request.args.get('page', 1, type=int)
    pagination = u.followers.paginate(page, per_page=10, error_out=False)
    follows = [{
        'user': item.follower,
        'timestamp': item.timestamp
    } for item in pagination.items]
    return render_template(
        'followers.html',
        title=u'的粉丝',
        user=u,
        pagination=pagination,
        follows=follows)


@app.route('/followed-by/<username>')
def followed_by(username):
    u = User.query.filter_by(username=username).first()
    page = request.args.get('page', 1, type=int)
    pagination = u.followed.paginate(page, per_page=10, error_out=False)
    follows = [{
        'user': item.followed,
        'timestamp': item.timestamp
    } for item in pagination.items]
    return render_template(
        'followers.html',
        title=u'的关注',
        user=u,
        pagination=pagination,
        follows=follows)


@app.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        flash(u'你的个人信息已经被更改')
        db.session.add(current_user)  # 更新个人资料
        db.session.commit()
        return redirect(url_for('blog.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)


@app.route('/edit-profile/<int:id>', methods=['POST'])
@login_required
@permission_required(Permission.ADMINISTRATOR)
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdministratorForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.itsrole = Role.query.get(form.role.data)
        user.name = form.name.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        flash(u'该用户的信息已经更新了')
        return redirect(url_for('blog.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('edit_profile.html', form=form, user=user)


@app.route('/edit/<int:id>')
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and \
            not current_user.can(Permission.ADMINISTRATOR):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('blog.post', id=post.id))
    form = PostForm()
    form.title.data = post.title
    form.body.data = post.body
    return render_template('edit_post.html', form=form)


@app.route('/moderate', methods=['GET'])
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate():
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=10, error_out=False)
    comments = pagination.items
    return render_template(
        'moderate.html', comments=comments, pagination=pagination, page=page)


@app.route('/moderate/disable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_disable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = True
    db.session.add(comment)
    db.session.commit()
    return redirect(
        url_for('blog.moderate', page=request.args.get('page', 1, type=int)))


@app.route('/moderate/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = False
    db.session.add(comment)
    db.session.commit()
    return redirect(
        url_for('blog.moderate', page=request.args.get('page', 1, type=int)))


@app.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)


@app.route('/shutdown')
def server_shutdown():
    if not current_app.testing:
        abort(404)
    shutdown = request.environ.get('werkzeug.server,shutdown')
    if not shutdown:
        abort(500)
    shutdown()
    return '-----Shutting down------'


@app.after_app_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= current_app.config['MISSOURI_SLOW_DB_QUERY_TIME']:
            current_app.logger.warning(
                'Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n'
                % (query.statement, query.parameters, query.duration,
                   query.context))
    return response

src/templates/base.html
{% extends 'bootstrap/base.html' %} 
    {% block head %} 
        {{ super() }} 
        {% include 'component/_header.html' %} 
    {% endblock %} 
    
    {% block styles %}
        {{ super() }}

        <!-- Material Design fonts -->
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">
        <!-- Bootstrap Material Design -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'bootstrap-material-design.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'ripples.min.css') }}">
        <!-- Dropdown.js -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'jquery.dropdown.css') }}">
        <!-- codehilite -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'codehilite.css') }}">

        <style>
            body {
                padding-top: 70px
            }
        </style>
    {% endblock %}

    {% block navbar %}
        {% include 'component/_navbar.html' %}
        {# {{ nav.top.render() }} #}
    {% endblock %}

    {% block content %}
        {{ super() }}
        <div id="container">
            <div id="row">
            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button class="close" type="button" data-dismiss="alert">&times;</button> {{ message }}
                </div>
            {% endfor %}
            </div>
        </div>
    {% endblock %}

    {% block scripts %}
        {{ super() }}
        {{ moment.include_moment() }}
        {{ moment.lang("zh-CN") }}

        <script src="{{ url_for('static', filename = 'material.js') }}"></script>
        <script src="{{ url_for('static', filename = 'ripples.min.js') }}"></script>
        <script>
        $.material.init();
        </script>

        <!-- Dropdown.js -->
        <script src="{{ url_for('static', filename = 'jquery.dropdown.js') }}"></script>
        <script>
        $("select").dropdown();
        </script>
    {% endblock %}

src/templates/blog.html
{% extends 'md_editor.html' %}

{% block title %}写博客{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>写博客</h1>
    </div>
</div>
{{ super() }}
{% endblock %}

src/templates/confirm.html
<p>亲爱的 {{ user.username }},</p>
<p>确认您的用户<a href="{{ url_for('auth.confirm', token=token, _external=True) }}">请点击这里</a>。</p>
<p>同样,你可以复制下面的链接到浏览器的地址导航条上</p>
<p>{{ url_for('auth.confirm', token=token, _external=True) }}</p>

src/templates/edit_post.html
{% extends 'md_editor.html' %}
{% block title %}编辑博客{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header ">
        <h1>编辑博客</h1>
    </div>
</div>
{{ super() }}
{%endblock%}

src/templates/edit_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}编辑个人信息{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>编辑您的信息</h1>
    </div>
    <div class="container">
        <form method="post">
            {{ wtf.quick_form(form) }}
        </form>
    </div>
{% endblock %}

src/templates/followers.html
{% extends 'base.html' %}
{% import 'include/_macros.html' as macros %}

{% block title %}
    {{ user.username }}{{ title }}
{% endblock %}

{% block content %}
    <div class="page-header">
        <h2>{{ user.username }}{{ title }}</h2>
    </div>
    <table class="table table-hover followers">
        <thead><tr><th>用户名</th><th>时间</th></tr></thead>
        {% for follow in follows %}
            {% if follow.user != user %}
            <tr>
                <td>
                    <a href="{{ url_for('main.user',username=follow.user.username) }}">
                        <img class="img-rounded" src="{{ follow.user.gravatar(size=32) }}">
                        {{ follow.user.username }}
                    </a>
                </td>
                <td>
                {{ moment(follow.timestamp).format('L') }}
                </td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>
    <div class="pagination">
        {{ macros.pagination_widget(pagination, 'main.followers',username=user.username) }}
    </div>
{% endblock %}

src/templates/index.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% import 'component/_macros.html' as macros %} {% block title %}首页{% endblock %}
{% block content %}
{{ super() }}

<div class="container">
    <div class="page-header">
        <h1>
            {% if current_user.is_authenticated %}
            欢迎回来, {{ current_user.username }}
            {% else %}
            文章列表
            {% endif %}
        </h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12 well bs-component">
            <div class="post-tabs">
                <ul class="nav nav-tabs">
                    <li {% if not show_followed %}class="active" {% endif %}>
                        <a href="{{ url_for('blog.show_all') }}">所有文章</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li {% if show_followed %}class="active" {% endif %}>
                        <a href="{{ url_for('blog.show_followed') }}">我的关注</a>
                    </li>
                    {% endif %}
                </ul>
            </div>

            {% include 'component/_post.html' %}
            <nav class="text-center">
                <ul class="pagination">
                    {{ macros.pagination_widget(pagination, 'blog.index') }}
                </ul>
            </nav>
        </div>
    </div>
</div>

{% endblock %}
{% block scripts %}
    {{ super() }}
    {{ pagedown.include_pagedown() }}
{% endblock %}

src/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block head %}
    {{ super() }}
    <style type="text/css">
        #loginlength {
            width: 35%;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="page-header">
        <div class="container">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        <form method="post">
            {{ wtf.quick_form(form) }}
        </form>
    </div>
{% endblock %}

src/templates/md_editor.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    {{ super() }}
    <div class="container">
        <div class="row well">
            <form method="post" class="form " role="form">
            {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.title.label }}
                    {{ form.title(id="title", class="form-control" )}}
                </div>
                <div class="form-group">
                    {{ form.body.label }}
                    <div class="row">
                        <div class="col-md-6 " >
                            <div class="panel panel-default", style="height: 600px;">
                                <div class="panel-heading", style="height: 50px;">编辑区</div>
                                <div class="panel-body", style="height: 550px;">
                                    {{ form.body(only_input=True, style="height: 100%;width:100%;") }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6" >
                            <div class="panel panel-default", style="height: 600px;">
                                <div class="panel-heading", style="height: 50px;">预览区</div>
                                <div class="panel-body", style="height: 550px;">
                                    {{ form.body(only_preview=True) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group pull-right">
                    {{ form.submit(class="btn btn-raised") }}
                </div>
            </form>
        </div>
    </div>

    <style>
    #flask-pagedown-body{
        border-style: none;
        resize: none;
    }
    .flask-pagedown-preview{
        overflow-x:hidden;
        overflow-y: auto;
        height: 100%;
    }
    .flask-pagedown{
        height: 100%;
    }
    .panel-body img{ max-width: 100%; display: block; }
    </style>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js"></script>
    <script type="text/javascript">
        var converter = new showdown.Converter();
        function flask_pagedown_converter(text){
            return converter.makeHtml(text);
        }
    </script>
{% endblock %}

src/templates/moderate.html
{% extends 'base.html' %}
{% import "include/_macros.html" as macros %}

{% block content %}
    <div class="page-header">
        <h1>管理评论</h1>
    </div>
    {% set moderate = True %}
    {% include "component/_comment.html" %}
    <div class="pagination">
        {{ macros.pagination_widget(pagination, 'blog.moderate') }}
    </div>
{% endblock %}

src/templates/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "component/_macros.html" as macros %}

{% block content %}
{{ super() }}
<div class="container">
    <div class="page-header ">
        <h1>{{ posts[0].title }}</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12 well">
            {% set post_body = True %}
            {% include "component/_post.html" %}
            {% include "component/_comment.html" %}
            <nav class="text-center">
            <div class="pagination">
                {{ macros.pagination_widget(pagination, 'blog.post', id=posts[0].id) }}
            </div>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 well">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endblock %}

src/templates/register.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block head %}
    {{ super() }}
    <style type="text/css">
        #registerlength {
            width: 35%;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="page-header">
        <div class="container">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        <form method="post">
            {{ wtf.quick_form(form) }}
        </form>
    </div>
{% endblock %}

src/templates/unconfirmed.html
{% extends "base.html" %}
{% block title %}确认您的帐号{% endblock %}
{% block content %}
    <h1>
        您好,{{ current_user.username }}
    </h1>
    <h3>
        您至今还未确认您的帐号
    </h3>
    <p>
        在您可以浏览之前您需要先确认您的帐号。
        检查您的邮箱,应该收到了一份确认链接的邮件
    </p>
    <p>
        您是否重新需要一份邮件?
        <a href="{{ url_for('auth.resend_email') }}">请点击这里</a>
    </p>
{% endblock %}

src/templates/user.html
{% extends 'base.html' %}
{% block title %}个人资料{% endblock %}
{% block content %}
{{ super() }}
<div class="container">
    <div class="row well">
        <div class=" col-md-3 col-xs-4">
            <img class="img-circle profile-thumbail pull-right" src="{{ user.gravatar(size=128) }}" >
        </div>
        <div class="profile-header col-md-9 col-xs-8">
            <h1>{{ user.username }}</h1>
            {% if user.name or user.location %}
            <p>
                {% if user.name %}{{ user.name }}{% endif %} {% if user.location %}
                <a href="http://map.baidu.com/?q={{ user.location }}">{{ user.location }}</a> {% endif %}
            </p>
            {% endif %} {% if current_user.is_authenticated %}
            <p>
                <a href="mailto:{{ user.email }}">{{ user.email }}</a>
            </p>
            {% endif %} {% if user.about_me %}
            <p>{{ user.about_me }}</p>
            {% endif %}
            <p>注册时间:{{ moment(user.member_since).format('L') }}</p>
            <p>上次登陆时间:{{ moment(user.last_seen).fromNow() }}</p>
            <p>
                {% if user == current_user %}
                <a class="btn btn-raised" href="{{ url_for('blog.edit_profile') }}">
                    编辑信息
                </a> {% endif %} {% if current_user.is_administrator() %}
                <a class="btn btn-danger" href="{{ url_for('blog.edit_profile_admin', id=user.id) }}">
                    编辑信息[管理员]
                </a> {% endif %}
            </p>
            {% if current_user.can(Permission.FOLLOW) and user != current_user %} {% if not current_user.is_following(user) %}
            <a href="{{ url_for('blog.follow', username=user.username) }}" class="btn btn-primary">关注</a> {% else %}
            <a href="{{ url_for('blog.unfollow', username=user.username) }}" class="btn btn-default">不关注</a> {% endif %}
            {% endif %}
            <a href="{{ url_for('blog.followers',username=user.username) }}">
                <span class="badge">粉丝人数: {{ user.followers.count() - 1 }}</span>
            </a>
            <a href="{{ url_for('blog.followed_by',username=user.username) }}">
                <span class="badge">关注人数: {{ user.followed.count() - 1 }}</span>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-xs-12 well">
            <h3>{{ user.username }}发表的文章</h3>
            {% include 'component/_post.html' %}
        </div>
    </div>
</div>
{% endblock %}